# 빅분기 실기 1유형

In [1]:
import seaborn as sns
import pandas as pd

In [2]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

## 기초탐색 (Tips 데이터를 이용한 문제)

In [3]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
# 문제1 - total_bill 변수의 제 1사분위수를 구하고 정수값으로 출력하시오.
result = df['total_bill'].quantile(0.25)
result = int(result)
print(result)

13

In [ ]:
# 문제2 - total_bill 값이 20이상 25이하인 데이터의 수를 구하시오
print(df[:][df['total_bill'].between(20, 25)].shape[0])
print(len(df[:][df['total_bill'].between(20, 25)]))

42
42

In [ ]:
#문제3 - tip변수의 IQR값을 구하시오, (IQR = Q3 - Q1 (3사분위수 - 1사분위수))
q3, q1 = df['tip'].quantile([0.75, 0.25])
# print(q3, q1)
IQR = q3 - q1
print(IQR)

1.5625

In [5]:
# 문제4 - tip변수의 상위 10개 값의 총합을 구하여 소수점을 버리고, 정수를 출력하시오
result = df.sort_values(by='tip', ascending=False).iloc[0:10]
print(result)
# print(int(result['tip'].sum()))

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
214       28.17   6.50  Female    Yes   Sat  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
239       29.03   5.92    Male     No   Sat  Dinner     3
88        24.71   5.85    Male     No  Thur   Lunch     2

In [ ]:
# 문제5 - 전체 데이터에서 sex가 Female 인 비율이 얼마인지 소수점 첫째 자리까지 출력하시오
sex_f = df[['sex']][df['sex'] == 'Female'].shape[0]
sex_all = df.shape[0]
# print(sex_f, sex_all)

print(round(sex_f / sex_all, 1))

0.4

In [ ]:
# 문제6 - 첫 번째 행부터 순서대로 10개 뽑은 후, total_bill열의 평균값을 반올림하여 정수로 출력하시오
result = df.iloc[0:10]
# print(result)

print(round(result['total_bill'].mean()))

19

In [ ]:
# 문제7 - 첫 번째 행부터 순서대로 50%까지 데이터를 뽑아 tip변수의 중앙값을 구하시오

cnt_50 = df.shape[0] / 2
print(df.shape[0], cnt_50)

df_50 = df.iloc[0:122]
#print(df_50)

result = df_50['total_bill'].median()
print(result)

244 122.0
18.14

## 2. 결측치 처리 (mpg 데이터)

In [ ]:
df = sns.load_dataset('mpg')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
# 문제8 - 결측값이 있는 데이터의 수를 구하시오.
df.isnull().sum().sum()   # 결측치 : horsepower

6

In [ ]:
# 문제9 - horsepower 컬럼의 결측값을 horsepower의 평균값으로 대체하고, horsepower의 중앙값을 정수로 출력하시오
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())
df.isnull().sum()

result = df['horsepower'].median()
print(int(result))

95

In [ ]:
# 문제10 - horsepower컬럼에 결측치가 있는 행을 제거하고, 첫번째 행부터 순서대로 50%를 추출한후, 해당 데이터의 1사분위수를 구하시오

df1 = df.copy()
# df1.isnull().sum()

df1.dropna(inplace = True)
df1.isnull().sum()

cnt_50 = df.shape[0] / 2
# print(cnt_50)    # 199.0

result = df.iloc[0:199]
# print(result)

result2 = result['horsepower'].quantile(0.25)
print(result2)

86.0

## 3. 이상치 처리 (mpg 데이터)

In [ ]:
# 문제11 - clynder가 3인 자동차와 8인 자동차 그룹의 mpg 평균값 차이를 절대값 정수로 출력하시오
df.head()

c_3 = df['mpg'][df['cylinders'] == 3].mean()
c_8 = df['mpg'][df['cylinders'] == 8].mean()

# print(c_3, c_8)

print(int(abs(c_3 - c_8)))

5

In [ ]:
# 문제12 - horsepower 변수를 z-score 표준화를 진행하고, 이상치를 구하시오. 이상치는 z값이 1.5를 초과하거나 -1.5미만인 값이다.
#          z-score 표준화 : z = (x - 평균) / 표준편차

In [ ]:
_mean = df1['horsepower'].mean()
_std = df1['horsepower'].std()
# print(_mean, _std)

df1['z'] = (df1['horsepower'] - _mean) / _std
cond1 = df1['z'] > 1.5
cond2 = df1['z'] < -1.5
print(df1[:][cond1 | cond2].shape[0])

39

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
df['z'] = ss.fit_transform(df[['horsepower']])

cond1 = df['z'] > 1.5
cond2 = df['z'] < -1.5
print(df[:][cond1 | cond2].shape[0])

39

In [ ]:
# 문제13 - mpg컬럼을 min-max정규화를 진행한 후, 0.8보다 큰 값을 가지는 레코드 수를 구하시오.
#          min-max scaling : (x - min) / (max - min)

In [ ]:
_min = df1['mpg'].min()
_max = df1['mpg'].max()
# print(_min, _max)

df1['min-max'] = (df1['mpg'] - _min) / (_max - _min)

cond1 = df1['min-max'] > 0.8
print(df1[:][cond1].shape[0])

10

In [ ]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()

df1['mpg_mm'] = mms.fit_transform(df1[['mpg']])
cond1 =  df1['mpg_mm'] > 0.8
print(df1[:][cond1].shape[0])

10

In [ ]:
# 문제14 - weight 컬럼에 대해 상자그림(박스플롯) 기준으로 이상치의 갯수를 구하시오
#          ub = q3 + (1.5 * IQR)
#          lb = q1 - (1.5 * IQR)
#          IQR = q3 - q1

df1 = df.copy()

q3, q1 = df1['weight'].quantile([0.75, 0.25])
IQR = q3 - q1
ub = q3 + (1.5 * IQR)
lb = q1 - (1.5 * IQR)
print(q3, q1, IQR, ub, lb)

cond1 = df1['weight'] < lb
cond2 = df1['weight'] > ub

print(df1['weight'][cond1 & cond2].shape[0])

3608.0 2223.75 1384.25 5684.375 147.375
0

## 4. 데이터분석 (mpg 데이터)

In [ ]:
# 문제15 - model_year가 80보다 큰 차량 중에 mpg값이 가장 큰 차량의 horsepower 값을 합산하여 출력하시오

result = df[:][df['model_year'] > 80].sort_values(by='mpg', ascending = False)
# print(result.head(10))

max_mpg = int(result.iloc[0]['mpg'])
# print(max_mpg)

print(result['horsepower'][result['mpg'] == max_mpg].sum())

52.0

In [ ]:
# 문제16 - origin이 usa, europe인 데이터의 horsepower 표준편차값의 차이를 절대값으로 소수 첫째 자리까지 출력하시오.
import numpy as np
# df.info()
# df.describe()
df.head(5)
# df['origin'].unique()

std_usa = np.std( df['horsepower'][df['origin'] == 'usa'])
std_europe = np.std(df['horsepower'][df['origin'] == 'europe'])
# print(usa, europe)

result = round(abs(std_usa - std_europe), 1)
print(result)

19.4

In [ ]:
# 문제17 - origin별로 그룹화하여 weight 평균값을 산출하고, 평균값이 높은 그룹의 weight 3사분위 수 값을 구하시오.
# df.head(3)
# df.isnull().sum()
# df.dropna(inplace = True)
# df.isnull().sum()
result = df.groupby('origin')['weight'].mean().reset_index()
# print(result)

result.sort_values(by = 'weight', ascending = False)    # europe
print(result)

result = df['weight'][df['origin'] == 'europe'].quantile(0.75)
print(result)

   origin       weight
0  europe  2423.300000
1   japan  2221.227848
2     usa  3361.931727
2769.75

In [ ]:
# 문제18 - name별로 그룹화하여, mpg 중앙값을 산출하고, 중앙값이 높은 그룹의 mpg 1사분위 수 값을 구하시오.
# df.info()
# df.isnull().sum()

result = df.groupby('name')['mpg'].median().reset_index()
#print(result)

result2 = result.sort_values(by = 'mpg', ascending = False)
print(result2)

result3 =df['mpg'][df['name'] == 'mazda glc']
print(result3.quantile(0.25))

                     name   mpg
176             mazda glc  46.6
170   honda civic 1500 gl  44.6
303  vw rabbit c (diesel)  44.3
301             vw pickup  44.0
300    vw dasher (diesel)  43.4
..                    ...   ...
192       mercury marquis  11.0
112            dodge d200  11.0
68              chevy c20  10.0
133             ford f250  10.0
163              hi 1200d   9.0

[305 rows x 2 columns]
46.6

In [ ]:
# 문제19 - horsepower 상위 10번째 값으로 상위 10개 값을 변환한 후, horsepower가 150 이상인 데이터를 추출하여, horsepower의 평균값을 반올림하여 정수로 출력하시오.
# df.head(3)

df1 = df.copy()
df1 = df1.sort_values(by='horsepower', ascending = False, ignore_index = True)
# df1.head(12)

a = df1.loc[9, 'horsepower']
# print(a)

df1.loc[0:9, 'horsepower'] = a
# print(df1.head(12))

result = df1['horsepower'][df1['horsepower'] >= 150].mean()
print(round(result))

171

In [ ]:
# 문제20 - name 변수에 mercury문구가 포함된 자동차의 mpg평균값을 정수로 출력하시오.
# df1.head(5)
df1 = df.copy()
cond1 = df1['name'].str.contains('mercury')
result = df1['mpg'][cond1].mean()
print(int(result))

19

In [ ]:
# 문제21 - horsepower와 weight의 상관계수를 소수 둘째자리 까지 구하시오
df1 = df.copy()

result = df1['horsepower'].corr(df1['weight'])
print(round(result, 2))

0.86

In [ ]:
# 문제22 - mpg와 가장 상관관계가 높은 수치형 변수를 구하시오.
df1 = df.copy()
# df1.info()
df1 = df1[['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year']]

corr_matrix = df1.corr()
#print(corr_matrix)

# Case1
result = corr_matrix['mpg'].sort_values(ascending = False)
# print(result)
print(result.index[1])      # model_year

# Case2
# result = corr_matrix['mpg'].drop(['mpg'])
# print(result)
# print(result.idxmax())      # model_year

model_year

In [ ]:
# 문제23 - mpg와 음의 상관관계가 가장 높은 수치형 변수를 구하여, 해당 변수의 중앙값을 구하시오
df1 = df.copy()
df1 = df1[['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year']]
corr_matrix = df1.corr()
# print(corr_matrix)
corr_matrix = corr_matrix['mpg'].drop('mpg')
corr_matrix = corr_matrix.sort_values()
print(corr_matrix)
# print(corr_matrix.idxmin())   # weight

a = corr_matrix.idxmin()
print(a)

result = df1[a].median()
print(result)

weight         -0.831741
displacement   -0.804203
cylinders      -0.775396
horsepower     -0.771437
acceleration    0.420289
model_year      0.579267
Name: mpg, dtype: float64
weight
2803.5

## 5.날짜처리

In [ ]:
import pandas as pd
df = pd.DataFrame({
    '날짜':['20220102', '20220105', None, '20230127', '20220203', '20220205', '20220915', '20230301', '20230203', '20230205', '20230315', '20230515'],
    '제품' : ['사과', '딸기', None, '딸기', '사과', None, '사과', '딸기', '사과', '딸기', '사과', '사과' ],
    '판매량' : [3, None, 5, 10, 10, 10, 15, 15, 20, None, 30, 40],
    '개당수익' : [300, 400, 500, 600, 400, 500, 500, 600, 600, 700, 600, 600]
})

In [ ]:
# 문제24 - 판매량 컬럼의 결측치를 최소값으로 대체하고 결측치가 있을 때와 최소값으로 대체했을때 평균값의 차이를 절대값 정수로 출력하시오
df1 = df.copy()
df1['판매량'] = df1['판매량'].fillna(df1['판매량'].min())
# print(df1['판매량'])

a = df['판매량'].mean()
b = df1['판매량'].mean()

print(int(abs(a - b)))

2

In [ ]:
# 문제25 - 22년 1분기 사과 매출액을 구하시오. (매출액 = 판매량 * 개당수익)
df1 = df.copy()

df1['매출액'] = df1['판매량'] * df1['개당수익']
# print(df1.head(10))

df1['날짜'] = pd.to_datetime(df1['날짜'])
# df1.info()

# df1['날짜'].dt.year / month / day

df1['년'] = df1['날짜'].dt.year
df1['월'] = df1['날짜'].dt.month
df1['일'] = df1['날짜'].dt.day
df1['분기'] = df1['날짜'].dt.quarter

cond1 = df1['년'] == 2022
cond2 = df1['분기'] == 1
cond3 = df1['제품'] == '사과'

print(df1['매출액'][cond1 & cond2 & cond3].sum())

4900.0

In [ ]:
# 문제26 - 22년과 23년 촐 매출액의 차이를 절대 값으로 구하시오.
df1 = df.copy()

df1['매출액'] = df1['판매량'] * df1['개당수익']
df1['날짜'] = pd.to_datetime(df1['날짜'])

df1['년'] = df1['날짜'].dt.year

sal_22 = df1['매출액'][df1['년'] == 2022].sum()
sal_23 = df1['매출액'][df1['년'] == 2023].sum()

print(abs(sal_22 - sal_23))

51600.0

In [ ]:
help(pd)

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# 문제27 - 23년  총 매출액이 큰 제품의 23년 판매량을 구하시오
df1 = df.copy()

df1['날짜'] = pd.to_datetime(df1['날짜'])
df1['매출액'] = df1['판매량'] * df1['개당수익']
df1['년'] = df1['날짜'].dt.year

cond1 = df1['년'] == 2022
cond2 = df1['년'] == 2023

pname = df1[cond1].groupby('제품')['매출액'].sum().idxmax()  # 22년 매출이 큰 제품
print(f'pname : {pname}')
cond3 = df1['제품'] == pname

result = df1['판매량'][cond2 & cond3].sum()
print(result)

pname : 사과
90.0

In [ ]:
# 문제28 - 매출액이  4천원 초과, 1만원 미만인 데이터 수를 출력하시오
df1 = df.copy()

df1['매출액'] = df1['판매량'] * df1['개당수익']

cond1 = df1['매출액'] > 4000
cond2 = df1['매출액'] < 10000

print(df1[:][cond1 & cond2].shape[0])

4

In [ ]:
df1 = df.copy()

# df에 시간 데이터 임의로 입력
time = pd.date_range('2023-07-24 12:00:00', '2023-07-25 14:50:30', periods = 12)
# print(time)

df1['time'] = time

df1 = df1.drop('날짜', axis = 1)
display(df1)

      제품   판매량  개당수익                          time
0     사과   3.0   300 2023-07-24 12:00:00.000000000
1     딸기   NaN   400 2023-07-24 14:26:24.545454545
2   None   5.0   500 2023-07-24 16:52:49.090909090
3     딸기  10.0   600 2023-07-24 19:19:13.636363636
4     사과  10.0   400 2023-07-24 21:45:38.181818181
5   None  10.0   500 2023-07-25 00:12:02.727272727
6     사과  15.0   500 2023-07-25 02:38:27.272727272
7     딸기  15.0   600 2023-07-25 05:04:51.818181818
8     사과  20.0   600 2023-07-25 07:31:16.363636363
9     딸기   NaN   700 2023-07-25 09:57:40.909090909
10    사과  30.0   600 2023-07-25 12:24:05.454545454
11    사과  40.0   600 2023-07-25 14:50:30.000000000

In [ ]:
# 문제29 - 23년7월24일 15 ~ 23시 사이 전체 제품 판매량을 구하시오

cond1 = df1['time'].between('2023-07-24 15:00', '2023-07-24 23:00')

result = df1['판매량'][cond1].sum()
print(result)

25.0

In [ ]:
# 문제30 - 7월24일 12:00 ~ 21:00 까지의 딸기의 매출액 총합을 구하시오.
df1['매출액'] = df1['판매량'] * df1['개당수익']
cond1 = df1['time'].between('2023-07-24 12:00', '2023-07-24 21:00')
cond2 = df1['제품'] == '딸기'

result = df1['매출액'][cond1 & cond2].sum()
print(result)

6000.0

In [ ]:
df1 = df.copy()
# df1['제품'] = df1['제품'].dropna(inplace=True)
df1 = df1.dropna()
# print(df1)

cond1 = df1['제품'].str.contains('딸')

result = df1[:][cond1]
print(result)

---
## 암기 필요항목

### 조건 조회함수

In [ ]:
# 조건 조회함수
emp['sal'].between(100, 200)          # 범위 조회
emp['job'].isin([10, 20])             # 다중 조건 조회
emp['comm'].isnull()                  # 결측치 확인
emp['ename'].apply(lambda 함수)       # 람다식 적용

#Ex) emp['ename'].apply(lambda x : x[0] == 'A')

### 데이터 정렬하기

In [ ]:
# 데이터 정렬하기
emp[:].sort_values(by = 'ename', ascending = False)

### 날짜 처리

In [ ]:
# 날짜 처리
df1['날짜'] = pd.to_datetime(df1['날짜'])   # 날짜 형변환

df1['년'] = df1['날짜'].dt.year           # 년
df1['월'] = df1['날짜'].dt.month          # 월
df1['일'] = df1['날짜'].dt.day            # 일
df1['분기'] = df1['날짜'].dt.quarter      # 분기

### 문자함수

In [ ]:
# 문자함수
#형식 : 문자열.문자함수

import seaborn as sns
import pandas as pd
tit = sns.load_dataset('titanic')
print(tit.head())
print(tit.info())

print(f"upper : {tit['embark_town'].str.upper()}")                 # 대문자로 변환
tit['embark_town'].str.lower()                                     # 소문자로 변환
tit['embark_town'].str.capitalize()                                # 문자열의 첫 글자만 대문자로 변환하고 나머지는 소문자로 변환
tit['embark_town'].str.slice(start = 0, stop = 2)                  # 문자열 자르기
tit['embark_town'].str.len()                                       # 문자열 길이 구하기
tit['embark_town'].str.strip()                                     # 공백제거 (매개변수로 제거할 문자를 지정할 수 있음 (eX) str.strip('O') )
tit['embark_town'].str.lstrip()                                    # 왼쪽 공백 제거 (매개변수로 제거할 문자를 지정할 수 있음 (eX) str.lstrip('O') )
tit['embark_town'].str.rstrip()                                    # 오른쪽 공백 제거 (매개변수로 제거할 문자를 지정할 수 있음 (eX) str.rstrip('O') )
tit['embark_town'].str.replace('Southampton', 'Northampton')       # 문자열 변환 ('Southampton' => 'Northampton')
tit['embark_town'].str.find('Southampton')                         # 문자열 위치 찾기 (없으면 -1)
tit['embark_town'].str.contains('South')                           # 해당 문자열을 포함하는지 여부 확인 (True or False)

### 집계 함수

In [ ]:
# 집계 함수
import seaborn as sns
import pandas as pd
tit = sns.load_dataset('titanic')
# print(tit.head())
# print(tit.info())

print(f"max: {tit['fare'].max()}")          # 최대값
print(f"min: {tit['fare'].min()}")          # 최소값
print(f"sum : {tit['fare'].sum()}")         # 합계값
print(f"mean : {tit['fare'].mean()}")       # 평균값
print(f"count : {tit['fare'].count()}")     # 개수합계
print(f"median : {tit['fare'].median()}")   # 중앙값
print(f"mode : {tit['fare'].mode()}")       # 최빈값

max: 512.3292
min: 0.0
sum : 28693.9493
mean : 32.204207968574636
count : 891
median : 14.4542
mode : 0    8.05
Name: fare, dtype: float64

### rank & qcut 함수
- rank 함수 : 순위 매기기
- qcut 함수 : 등급 나누기

In [ ]:
# rank 함수
df = sns.load_dataset('car_crashes')
# print(df.head())
# print(df.info())

df1 = df.copy()

# Case1
df1['순위_alcohol'] = df1['alcohol'].rank(method = 'dense', ascending = True)            # 순위 순번 매기기
# df1.sort_values(by='순위_alcohol')
# 등급 나누기
df1['alcohol_grade'] = pd.qcut(df1['순위_alcohol'], q = 5, labels = [1, 2, 3, 4, 5])     # 순위를 등급으로 나누기
df1.sort_values(by = ['순위_alcohol', 'alcohol_grade'])

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev,순위_alcohol,alcohol_grade
8,5.9,2.006,1.593,5.900,5.900,1273.89,136.05,DC,1.0,1
44,11.3,4.859,1.808,9.944,10.848,809.38,109.48,UT,2.0,1
23,9.6,2.208,2.784,8.448,8.448,777.18,133.35,MN,3.0,1
21,8.2,1.886,2.870,7.134,6.560,1011.14,135.63,MA,4.0,1
30,11.2,1.792,3.136,9.632,8.736,1301.52,159.85,NJ,5.0,1
37,12.8,4.224,3.328,8.576,11.520,804.71,104.61,OR,6.0,1
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA,7.0,1
46,12.7,2.413,3.429,11.049,11.176,768.95,153.72,VA,8.0,1
29,11.6,4.060,3.480,10.092,9.628,746.54,120.21,NH,9.0,1
47,10.6,4.452,3.498,8.692,9.116,890.03,111.62,WA,10.0,1
32,12.3,3.936,3.567,10.824,9.840,1234.31,150.01,NY,11.0,1
5,13.6,5.032,3.808,10.744,12.920,835.50,139.91,CO,12.0,2
6,10.8,4.968,3.888,9.396,8.856,1068.73,167.02,CT,13.0,2
10,15.6,2.964,3.900,14.820,14.508,913.15,142.80,GA,14.0,2
15,15.7,2.669,3.925,15.229,13.659,649.06,114.47,IA,15.0,2
22,14.1,3.384,3.948,13.395,10.857,1110.61,152.26,MI,16.0,2
20,12.5,4.250,4.000,8.875,12.375,1048.78,192.70,MD,17.0,2
45,13.6,4.080,4.080,13.056,12.920,716.20,109.61,VT,18.0,2
14,14.5,3.625,4.205,13.775,13.775,710.46,108.92,IN,19.0,2
39,11.1,3.774,4.218,10.212,8.769,1148.99,148.58,RI,20.0,2
16,17.8,4.806,4.272,13.706,15.130,780.45,133.80,KS,21.0,2
13,12.8,4.608,4.352,12.032,12.288,803.11,139.15,IL,22.0,3
12,15.3,5.508,4.437,13.005,14.994,641.96,82.75,ID,23.0,3
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK,24.0,3
19,15.1,5.738,4.530,13.137,12.684,661.88,96.57,ME,25.0,3
49,13.8,4.968,4.554,5.382,11.592,670.31,106.62,WI,26.0,3
28,14.7,5.439,4.704,13.965,14.553,1029.87,138.71,NV,27.0,3
35,14.1,3.948,4.794,13.959,11.562,697.73,133.52,OH,28.0,3
7,16.2,6.156,4.860,14.094,16.038,1137.87,151.48,DE,29.0,3
17,21.4,4.066,4.922,16.692,16.264,872.51,137.13,KY,30.0,3
31,18.4,3.496,4.968,12.328,18.032,869.85,120.75,NM,31.0,3
9,17.9,3.759,5.191,16.468,16.826,1160.13,144.18,FL,32.0,4
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ,33.0,4
33,16.8,6.552,5.208,15.792,13.608,708.24,127.82,NC,33.0,4
27,14.9,1.937,5.215,13.857,13.410,732.28,114.82,NE,34.0,4
24,17.6,2.640,5.456,1.760,17.600,896.07,155.77,MS,35.0,4
25,16.1,6.923,5.474,14.812,13.524,790.32,144.45,MO,36.0,4
50,17.4,7.308,5.568,14.094,15.660,791.14,122.04,WY,37.0,4
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL,38.0,4
38,18.2,9.100,5.642,17.472,16.016,905.99,153.86,PA,39.0,4
42,19.5,4.095,5.655,15.990,15.795,767.91,155.57,TN,40.0,4
36,19.9,6.368,5.771,18.308,18.706,881.51,178.86,OK,41.0,5
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR,42.0,5
41,19.4,6.014,6.402,19.012,16.684,669.31,96.87,SD,43.0,5
48,23.8,8.092,6.664,23.086,20.706,992.61,152.56,WV,44.0,5
18,20.5,7.175,6.765,14.965,20.090,1281.55,194.78,LA,45.0,5
11,17.5,9.450,7.175,14.350,15.225,861.18,120.92,HI,46.0,5
43,19.4,7.760,7.372,17.654,16.878,1004.75,156.83,TX,47.0,5
26,21.4,8.346,9.416,17.976,18.190,816.21,85.15,MT,48.0,5
40,23.9,9.082,9.799,22.944,19.359,858.97,116.29,SC,49.0,5
34,23.9,5.497,10.038,23.661,20.554,688.75,109.72,ND,50.0,5